"""Build the ELOR wordmark: Cormorant Garamond capitals with a dot-cluster O."""
import math, os, sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.misc.transform import Transform

FONT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "CormorantGaramond-Light.woff")

f = TTFont(FONT)
upem = f["head"].unitsPerEm
gs = f.getGlyphSet()
cmap = f.getBestCmap()
hmtx = f["hmtx"]

CAP = 100.0                 # cap height in output units
capH = f["OS/2"].sCapHeight if hasattr(f["OS/2"], "sCapHeight") else upem * 0.7
S = CAP / capH              # font units -> output units


def glyph(ch):
    name = cmap[ord(ch)]
    pen = SVGPathPen(gs, ntos=lambda v: f"{v:.2f}")
    # flip y (font y-up -> svg y-down), scale, baseline at y=0
    gs[name].draw(TransformPen(pen, Transform(S, 0, 0, -S, 0, 0)))
    adv = hmtx[name][0] * S
    return pen.getCommands(), adv


# ---- layout -----------------------------------------------------------------
TRACK = 0.085 * CAP          # letterspacing, matches the reference's airy fit
GAP_O = 0.13 * CAP           # the cluster's sparse edge supplies its own optical space
R_CLUSTER = 0.66 * CAP       # cluster outer radius: reads a little larger than a cap O

parts, x = [], 0.0
for ch in "EL":
    d, adv = glyph(ch)
    parts.append((d, x))
    x += adv + TRACK

x += GAP_O
cx = x + R_CLUSTER
cy = -CAP / 2                # optical centre of the cap band
x = cx + R_CLUSTER + GAP_O

d, adv = glyph("R")
parts.append((d, x))
x += adv

W = x
PAD_X, PAD_TOP, PAD_BOT = 0.0, 0.0, 0.0


# ---- the cluster ------------------------------------------------------------
# A ring of crystals rather than a drawn O: an outer ring of alternating large
# and small drops, an inner ring offset between them, and a few loose sparks.
# Sizes are set by hand so the silhouette stays legible when the logo is 19px
# tall in the navbar, where anything under ~0.9% of the width disappears.
import random
rnd = random.Random(20260815)   # fixed seed: the logo must be byte-identical on rebuild


CLEAR = 0.030 * CAP          # minimum air between two drops


def fits(cand, placed):
    """Drops that touch fuse into a peanut shape and the cluster stops reading
    as scattered light, so every drop keeps a hard clearance from its neighbours."""
    x0, y0, s0 = cand
    for x1, y1, s1 in placed:
        if math.hypot(x0 - x1, y0 - y1) < (s0 + s1) * CAP + CLEAR:
            return False
    return True


def band(placed, n, r_lo, r_hi, s_lo, s_hi, phase=0.0, ang_jit=0.42):
    """Scatter n drops in an annulus. Angular jitter keeps the ring from reading
    as a mandala; even spacing is what made the first draft look mechanical."""
    out = []
    for i in range(n):
        for _attempt in range(400):
            a = phase + 2 * math.pi * (i + rnd.uniform(-ang_jit, ang_jit)) / n
            rr = rnd.uniform(r_lo, r_hi) * R_CLUSTER
            cand = (cx + rr * math.cos(a), cy + rr * math.sin(a), rnd.uniform(s_lo, s_hi))
            if fits(cand, placed + out):
                out.append(cand)
                break
    return out

dots = []
# Outer band carries the silhouette, so it holds the largest drops.
dots += band(dots, 15, 0.84, 1.00, 0.038, 0.105, phase=-math.pi / 2)
# Inner band gives the cluster depth without closing the counter.
dots += band(dots, 10, 0.46, 0.66, 0.026, 0.062, phase=-math.pi / 2 + 0.5)
# Three sparks thrown clear of the ring, so it reads as scattering light.
dots += band(dots, 3, 1.04, 1.11, 0.022, 0.034, phase=0.9, ang_jit=0.5)

# bounds
minx = min([0.0] + [d[0] - d[2] * CAP for d in dots])
maxx = max([W] + [d[0] + d[2] * CAP for d in dots])
miny = min([-CAP] + [d[1] - d[2] * CAP for d in dots])
maxy = max([0.0] + [d[1] + d[2] * CAP for d in dots])

M = 4.0
vb_x, vb_y = minx - M, miny - M
vb_w, vb_h = (maxx - minx) + 2 * M, (maxy - miny) + 2 * M


NOTE = ("<!-- ELOR wordmark. Generated by brand-assets/logo-src/build-logo.py, do not hand-edit.\n"
        "     Letterforms: Cormorant Garamond Light, converted to outlines.\n"
        "     The O is a scattered crystal cluster, not a drawn letter. -->")


def build(color):
    L = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="'
         f'{vb_x:.2f} {vb_y:.2f} {vb_w:.2f} {vb_h:.2f}" fill="{color}" role="img" '
         f'aria-label="ELOR">', NOTE]
    L.append('  <g id="letters">')
    for d, ox in parts:
        L.append(f'    <path transform="translate({ox:.2f} 0)" d="{d}"/>')
    L.append('  </g>')
    L.append('  <g id="cluster">')
    for dx, dy, s in dots:
        L.append(f'    <circle cx="{dx:.2f}" cy="{dy:.2f}" r="{s * CAP:.2f}"/>')
    L.append('  </g>')
    L.append('</svg>')
    return "\n".join(L) + "\n"


def build_mark(color, box=96, pad=0.055, bg=None, radius=None):
    """The full cluster alone, centred in a square: avatars, stamps, large icons."""
    span = max(max(abs(d[0] - cx) + d[2] * CAP for d in dots),
               max(abs(d[1] - cy) + d[2] * CAP for d in dots))
    k = (box / 2) * (1 - 2 * pad) / span
    L = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {box} {box}" '
         f'role="img" aria-label="Elor">']
    if bg:
        L.append(f'  <rect width="{box}" height="{box}" rx="{radius}" fill="{bg}"/>')
    L.append(f'  <g fill="{color}">')
    for dx, dy, s in dots:
        L.append(f'    <circle cx="{box/2 + (dx - cx) * k:.2f}" '
                 f'cy="{box/2 + (dy - cy) * k:.2f}" r="{s * CAP * k:.2f}"/>')
    L.append('  </g>')
    L.append('</svg>')
    return "\n".join(L) + "\n"


def build_stacked(word_color, tag_color, bg=None):
    """Print lockup: wordmark with the LIGHTING descriptor outlined beneath it.

    The site sets the descriptor as live Inter, but a brand kit has to travel to
    people without the font installed, so here it is converted to outlines.
    """
    tag_font = TTFont(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                   "Inter-Medium.woff"))
    tgs, tcmap = tag_font.getGlyphSet(), tag_font.getBestCmap()
    tup = tag_font["head"].unitsPerEm
    # Sized off the site lockup: .mark is 26px (cap 16.9px) against an 8.5px tag,
    # so the descriptor is roughly half the cap height, not a fraction of it.
    TAG_SIZE = 0.50 * CAP
    TRACK_TAG = 0.42 * TAG_SIZE          # matches .tag letter-spacing in the site CSS
    ts = TAG_SIZE / tup

    glyphs, tw = [], 0.0
    for ch in "LIGHTING":
        name = tcmap[ord(ch)]
        pen = SVGPathPen(tgs, ntos=lambda v: f"{v:.2f}")
        tgs[name].draw(TransformPen(pen, Transform(ts, 0, 0, -ts, 0, 0)))
        glyphs.append((pen.getCommands(), tw))
        tw += tag_font["hmtx"][name][0] * ts + TRACK_TAG
    tw -= TRACK_TAG

    GAP = 0.32 * CAP                     # site gap is 6px against a 16.9px cap
    tag_y = maxy + GAP + TAG_SIZE
    pad = 0.55 * CAP
    x0, y0 = vb_x - pad, vb_y - pad
    w_ = max(vb_w, tw + 2 * pad) + 2 * pad - (vb_w - vb_w)
    h_ = (tag_y - vb_y) + pad + pad
    tag_x = vb_x + (vb_w - tw) / 2       # descriptor centred under the wordmark

    L = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="'
         f'{x0:.2f} {y0:.2f} {w_:.2f} {h_:.2f}" role="img" aria-label="Elor Lighting">',
         NOTE]
    if bg:
        L.append(f'  <rect x="{x0:.2f}" y="{y0:.2f}" width="{w_:.2f}" '
                 f'height="{h_:.2f}" fill="{bg}"/>')
    L.append(f'  <g fill="{word_color}">')
    for d, ox in parts:
        L.append(f'    <path transform="translate({ox:.2f} 0)" d="{d}"/>')
    for dx, dy, s in dots:
        L.append(f'    <circle cx="{dx:.2f}" cy="{dy:.2f}" r="{s * CAP:.2f}"/>')
    L.append('  </g>')
    L.append(f'  <g fill="{tag_color}">')
    for d, ox in glyphs:
        L.append(f'    <path transform="translate({tag_x + ox:.2f} {tag_y:.2f})" d="{d}"/>')
    L.append('  </g>')
    L.append('</svg>')
    return "\n".join(L) + "\n"


def build_icon(color, box=64, bg=None, radius=8):
    """Favicon: a purpose-drawn ring, not a reduction of the cluster.

    The scattered cluster is built for the wordmark and turns to mush in a 16px
    browser tab. Thinning it down does not rescue it either: filtering by size
    breaks the ring open, and a size floor fuses neighbours. So the icon is drawn
    on its own terms, as eight drops on an even ring with alternating sizes, which
    is the same idea (crystals held in a circle) at a size that can carry it.
    """
    n, ring_r = 8, box * 0.29
    big, small = box * 0.088, box * 0.056
    L = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {box} {box}" '
         f'role="img" aria-label="Elor">']
    if bg:
        L.append(f'  <rect width="{box}" height="{box}" rx="{radius}" fill="{bg}"/>')
    L.append(f'  <g fill="{color}">')
    for i in range(n):
        a = -math.pi / 2 + 2 * math.pi * i / n
        L.append(f'    <circle cx="{box/2 + ring_r * math.cos(a):.2f}" '
                 f'cy="{box/2 + ring_r * math.sin(a):.2f}" '
                 f'r="{(big if i % 2 == 0 else small):.2f}"/>')
    L.append('  </g>')
    L.append('</svg>')
    return "\n".join(L) + "\n"


# ---- react components -------------------------------------------------------
# The nav and footer render the mark inline so it inherits colour from its
# context, so the same geometry is emitted as TSX rather than referenced as a file.
TSX_HEAD = ("/* GENERATED by brand-assets/logo-src/build-logo.py. Do not hand-edit.\n"
            " * Rerun the script to change the artwork. */\n")


def build_tsx_wordmark():
    L = [TSX_HEAD,
         "/**",
         " * The ELOR wordmark: Cormorant Garamond Light capitals with the O replaced",
         " * by a suspended cluster of crystal drops. Fills with currentColor, so the",
         " * caller decides pearl, ink or gold.",
         " */",
         "export function Wordmark({ className }: { className?: string }) {",
         "  return (",
         "    <svg",
         "      className={className}",
         f'      viewBox="{vb_x:.2f} {vb_y:.2f} {vb_w:.2f} {vb_h:.2f}"',
         '      fill="currentColor"',
         '      role="img"',
         '      aria-label="Elor"',
         "    >"]
    for d, ox in parts:
        L.append(f'      <path transform="translate({ox:.2f} 0)" d="{d}" />')
    for dx, dy, s in dots:
        L.append(f'      <circle cx="{dx:.2f}" cy="{dy:.2f}" r="{s * CAP:.2f}" />')
    L += ["    </svg>", "  );", "}", ""]
    return "\n".join(L)


def build_tsx_logo(box=96, pad=0.055):
    span = max(max(abs(d[0] - cx) + d[2] * CAP for d in dots),
               max(abs(d[1] - cy) + d[2] * CAP for d in dots))
    k = (box / 2) * (1 - 2 * pad) / span
    L = [TSX_HEAD,
         "/**",
         " * The Elor emblem: the wordmark's crystal cluster standing alone, squared up",
         " * for avatars, stamps and large icons. Fills with currentColor.",
         " * For favicons use /brand/favicon.svg instead, which is drawn separately so",
         " * it survives a 16px browser tab.",
         " */",
         "export function Logo({ className }: { className?: string }) {",
         "  return (",
         "    <svg",
         "      className={className}",
         f'      viewBox="0 0 {box} {box}"',
         '      fill="currentColor"',
         '      role="img"',
         '      aria-label="Elor"',
         "    >"]
    for dx, dy, s in dots:
        L.append(f'      <circle cx="{box/2 + (dx - cx) * k:.2f}" '
                 f'cy="{box/2 + (dy - cy) * k:.2f}" r="{s * CAP * k:.2f}" />')
    L += ["    </svg>", "  );", "}", ""]
    return "\n".join(L)


# ---- output -----------------------------------------------------------------
ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
def w(p, s):
    full = os.path.join(ROOT, p)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    open(full, "w").write(s)

# Nocturne palette, matching app/globals.css
PEARL, INK, GOLD, GOLD_HI, OBSIDIAN = "#ECE5D6", "#1E1912", "#E3C489", "#F4E4BC", "#0B0906"

# Runtime assets the site links to
w("public/brand/logo-wordmark.svg", build(PEARL))
w("public/brand/logo-wordmark-dark.svg", build(INK))
w("public/brand/logo-wordmark-gold.svg", build(GOLD))
w("public/brand/logo-mark.svg", build_mark(GOLD))
w("public/brand/favicon.svg", build_icon(GOLD_HI, box=64, bg=OBSIDIAN, radius=8))

# Inline components used by the nav and footer
w("components/ui/Wordmark.tsx", build_tsx_wordmark())
w("components/ui/Logo.tsx", build_tsx_logo())

# Canonical brand kit
w("brand-assets/svg/elor-logo-horizontal-on-dark.svg", build(PEARL))
w("brand-assets/svg/elor-logo-horizontal-on-light.svg", build(INK))
w("brand-assets/svg/elor-logo-horizontal-gold.svg", build(GOLD))
w("brand-assets/svg/elor-emblem-on-dark.svg", build_mark(PEARL))
w("brand-assets/svg/elor-emblem-on-light.svg", build_mark(INK))
w("brand-assets/svg/elor-emblem-gold.svg", build_mark(GOLD))
w("brand-assets/svg/elor-app-icon.svg", build_icon(GOLD_HI, box=512, bg=OBSIDIAN, radius=112))
w("brand-assets/svg/elor-logo-stacked-on-dark.svg", build_stacked(PEARL, "#B8935A"))
w("brand-assets/svg/elor-logo-stacked-on-light.svg", build_stacked(INK, "#9A7743"))

print(f"viewBox {vb_x:.1f} {vb_y:.1f} {vb_w:.1f} {vb_h:.1f}  ratio {vb_w/vb_h:.2f}  "
      f"dots {len(dots)}  cap/height {CAP/vb_h:.3f}")
